name: JMPT

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 358

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run index.py
        env:
          PYTHONUNBUFFERED: "1"
          PYTHONIOENCODING: "utf-8"
        run: |
          timeout 355m python3 -u index.py || true
